# Generated by Django 4.2.5 on 2023-10-03 06:29

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_student_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='contact_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
