# Generated by Django 4.2.5 on 2023-09-20 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_complain_complain_type_delete_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
