# Generated by Django 4.2.5 on 2023-10-09 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_student_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
