# Generated by Django 4.2.5 on 2023-10-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_complain_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='updatestatustime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
